name: Feature request
description: Ideas for widgets or improvements
labels: [enhancement]
body:
  - type: textarea
    id: idea
    attributes:
      label: What would you like Visor to do?
    validations:
      required: true
